server:
  servlet:
    context-path: /admin
  port: 80

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jdbc?useSSL=false
    username: root
    password: 123456
  profiles:
    active: cly

---
spring:
  profiles: alpha

db:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/cskaoyanmall?useSSL=false
  username: root
  password: 123456

---
spring:
  profiles: didi

db:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/cskaoyanmall?serverTimezone=GMT&useSSL=false
  username: root
  password: 123456

---
spring:
  profiles: cly

db:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/cskaoyanmall?serverTimezone=GMT&useSSL=false
  username: root
  password: 123456